#!/usr/bin/sh

# layouts and keybindings
# setxkbmap -layout "us,ru" -variant "dvorak," -option "grp:alt_shift_toggle,ctrl:nocaps,altwin:swap_lalt_lwin"
# xcape -t 200
$HOME/.launchers/keyboard-config.sh

# hide mouse cursor
unclutter -idle 10 &

# fix tearing
picom --daemon
# notifications
dunst &
# screenshots
flameshot &
# bluetooth
blueman-applet &

