
COLOR_WIDGET_FONT = "#eceff4"
COLOR_WS_ACTIVE = "#eceff4"
COLOR_WS_INACTIVE = "#d8dee9"
COLOR_PANEL_BACKGROUND = "#2e3440"
COLOR_CURRENT_SCREEN_BACKGROUND = "#4c566a"
COLOR_OTHER_SCREEN_BACKGROUND = "#3b4252"
COLOR_BORDER_FOCUS = "#4c566a"
COLOR_BORDER_NORMAL = "#3b4252"
COLOR_WIDGET_BACKGROUND_PRIMARY = "#434758"
COLOR_WIDGET_FOREGROUND_PRIMARY = "#e5e9f0"
COLOR_WIDGET_BACKGROUND_SECONDARY = "#2e3440"
COLOR_WIDGET_FOREGROUND_SECONDARY = "#e5e9f0"

COLOR_TAB_PANEL_BACKGROUND = "#2e3440"
COLOR_TAB_ACTIVE_BG = "#4c566a"
COLOR_TAB_ACTIVE_FG = "#e5e9f0"
COLOR_TAB_INACTIVE_BG = "#3b4252"
COLOR_TAB_INACTIVE_FG = "#e5e9f0"

FONT_NAME = "ubuntu"
FONT_SIZE = 13
ICON_FONT_SIZE = 26
FOREGROUND_COLOR = "#e5e9f0"
BAR_HEIGHT = 24

primary_font = {
    "font": "ubuntu",
    "fontsize": FONT_SIZE,
}

icon_font = {
    "fontsize": ICON_FONT_SIZE,
}

primary_colors = {
    "foreground": FOREGROUND_COLOR,
    "background": "#434758",
}

alternate_colors = {
    "foreground": FOREGROUND_COLOR,
    "background": "#2e3440",
}

panel_bar = {
    "size": BAR_HEIGHT,
    "background": COLOR_PANEL_BACKGROUND,
}
