title: sys.raccoon dotfiles

author:
  name: sysraccoon
  email: sysraccoon@gmail.com

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

show_excerpts: false

minima:
  social_links:
    github: sysraccoon
    youtube_channel: UCHjzFDGjrOXwyFd85eU0UhQ
    youtube_channel_name: sys.raccoon

theme: minima

