#!/usr/bin/env bash
set -euo pipefail

DOTFILES_PATH="$HOME/dotfiles"
CONFIG_PATH="$DOTFILES_PATH/configs"

if ! command -v nix &> /dev/null
then
    echo "Nix package manager required"
    echo "nixos wiki: https://nixos.wiki/wiki/Nix_Installation_Guide"
    echo "arch wiki: https://wiki.archlinux.org/title/Nix"
    exit 1
fi

echo "Configure nix channels and home-manager"

nix-channel --add https://github.com/nix-community/home-manager/archive/master.tar.gz home-manager
nix-channel --update home-manager

nix-shell '<home-manager>' -A install

mkdir -p "$HOME/.config"

echo "Link home-manager config"
ln -Tsf "$CONFIG_PATH/nixpkgs" "$HOME/.config/nixpkgs"

echo "Link .profile and .zshrc"
ln -Tsf "$CONFIG_PATH/shell/profile" "$HOME/.profile"
ln -Tsf "$CONFIG_PATH/zsh/zshrc" "$HOME/.zshrc"

echo "Link bin folder"
ln -Tsf "$DOTFILES_PATH/bin" "$HOME/bin"

