#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
SCRIPT_PATH=$(dirname "$SCRIPT")
SCRIPT_NAME=$(basename "$0")

mkdir -p "$HOME/.config"

config_names=(i3 polybar bat nvim kitty qutebrowser \
              qtile picom alacritty rofi picom dunst)
for module_name in "${config_names[@]}";
do
	echo "$SCRIPT_NAME: link $module_name"
    ln -Tsf "$SCRIPT_PATH/$module_name" "$HOME/.config/$module_name"
done

echo "$SCRIPT_NAME: link qutebrowser userscritps"
mkdir -p "$HOME/.local/share/qutebrowser"
ln -Tsf "$SCRIPT_PATH/qutebrowser/user_scripts" "$HOME/.local/share/qutebrowser/userscripts"

echo "$SCRIPT_NAME: link bin"
ln -Tsf "$SCRIPT_PATH/bin" "$HOME/bin"

echo "$SCRIPT_NAME: link launchers"
ln -Tsf "$SCRIPT_PATH/launchers" "$HOME/.launchers"

echo "$SCRIPT_NAME: link fonts"
ln -Tsf "$SCRIPT_PATH/fonts" "$HOME/.fonts"

echo "$SCRIPT_NAME: link gitconfig"
ln -Tsf "$SCRIPT_PATH/git/gitconfig" "$HOME/.gitconfig"

echo "$SCRIPT_NAME: link shell .profile"
ln -Tsf "$SCRIPT_PATH/shell/profile" "$HOME/.profile"

echo "$SCRIPT_NAME: link tmux config"
ln -Tsf "$SCRIPT_PATH/tmux/tmux.conf" "$HOME/.tmux.conf"

echo "$SCRIPT_NAME: setup nvim"
"$SCRIPT_PATH"/nvim/setup
echo "$SCRIPT_NAME: setup zsh"
"$SCRIPT_PATH"/zsh/setup
echo "$SCRIPT_NAME: setup x11"
"$SCRIPT_PATH"/x11/setup

