#!/usr/bin/env bash

SCRIPT=$(readlink -f $0)
SCRIPT_PATH=`dirname $SCRIPT`
SCRIPT_NAME=`basename $0`

ln -Tsf "$SCRIPT_PATH/xinitrc" "$HOME/.xinitrc"
ln -Tsf "$SCRIPT_PATH/xprofile" "$HOME/.xprofile"

