
alias nix-search-cache='nix-env -qa --json > /tmp/.nix-search-cache'
alias nix-search='nix search nixpkgs --offline'
alias nixos-up='nixos-rebuild switch --flake ~/dotfiles'
alias hm='home-manager'
alias hm-up='(export IMPURITY_PATH="${HOME}/dotfiles"; home-manager switch --impure --flake "${IMPURITY_PATH}/.#${USER}-impure")'
alias hm-up-pure='home-manager switch --flake ~/dotfiles'
alias na='nix-alien'
alias nix-sp='nix-shell --run zsh -p'
alias zipalign='na ~/Android/Sdk/build-tools/34.0.0/zipalign'
alias nltl='nix-locate --top-level'
