# If not running interactively, don't do anything
[[ $- != *i* ]] && {
  >&2 echo "interactive mode didn't support"
  exit 1;
}

ZSHRC_PATH=$(readlink -f "$HOME/.zshrc")

export DOTFILES_DIR="$HOME/dotfiles"
export ZSHRC_DIR=$(dirname "$ZSHRC_PATH")

MODULES=(
  # applications
  "xorg" # x11 features

  # languages
  "rust" # rust features
  "python" # python features

  # terminal
  "term-hotkeys" # enhance terminal hotkeys

  # tools
  "fzf" # fuzzy finder
  # "xbps" # void package manager
  "pacman" # pacman package manager
  "yay" # yay package manager
  "nix" # nix package manager

  # other
  "general" # enable general features
  "prompt" # enhance prompt
  # "tmux"
  "editor"
  "general.aliases"
  "git.aliases"
  "network.aliases"
  # "work" # work specific features (ignored in .gitignore)

  # external dependencies
  "antigen"
)

for module in ${MODULES[@]}; do
  if [[ -f "$ZSHRC_DIR/modules/$module.zsh" ]]; then
    source "$ZSHRC_DIR/modules/$module.zsh";
  fi
done

