
COLOR_WIDGET_FONT = "#eceff4"
COLOR_WS_ACTIVE = "#eceff4"
COLOR_WS_INACTIVE = "#d8dee9"
COLOR_PANEL_BACKGROUND = "#2e3440"
COLOR_CURRENT_SCREEN_BACKGROUND = "#4c566a"
COLOR_OTHER_SCREEN_BACKGROUND = "#3b4252"
COLOR_BORDER_FOCUS = "#4c566a"
COLOR_BORDER_NORMAL = "#3b4252"
COLOR_WIDGET_BACKGROUND_PRIMARY = "#434758"
COLOR_WIDGET_FOREGROUND_PRIMARY = "#e5e9f0"
COLOR_WIDGET_BACKGROUND_SECONDARY = "#2e3440"
COLOR_WIDGET_FOREGROUND_SECONDARY = "#e5e9f0"

FONT_NAME = "ubuntu"
FONT_SIZE = 13

BAR_HEIGHT = 24

