add_newline = true

format = """\
╭$directory$fill
╰$character\
"""

[character]
format = '$symbol'
success_symbol = '─% '
error_symbol = '─[%](red) '

[directory]
format = '─⌠ [$read_only]($read_only_style)[$path]($style) ⌡'
read_only = ' '

[fill]
symbol = '─'

